networks:
  minecraft-server-network:
    external: true

services:
  minecraft-server:
    image: ${MINECRAFT_SERVER_IMAGE_TAG}
    volumes:
      - ./minecraft-server-data:${DATA_PATH}
      - ./plugins:/plugins:ro
    environment:
      EULA: ${MINECRAFT_SERVER_EULA}
      TYPE: ${MINECRAFT_SERVER_TYPE}
      VERSION: ${MINECRAFT_SERVER_VERSION}
      MEMORY: ${MINECRAFT_SERVER_MEMORY}
      SERVER_NAME: ${MINECRAFT_SERVER_SERVER_NAME}
      MOTD: ${MINECRAFT_SERVER_MOTD}
      LEVEL_TYPE: ${MINECRAFT_SERVER_LEVEL_TYPE}
      LEVEL: ${MINECRAFT_SERVER_LEVEL}
      MODE: ${MINECRAFT_SERVER_MODE}
      FORCE_GAMEMODE: ${MINECRAFT_SERVER_FORCE_GAMEMODE}
      DIFFICULTY: ${MINECRAFT_SERVER_DIFFICULTY}
      HARDCORE: ${MINECRAFT_SERVER_HARDCORE}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: ${MINECRAFT_SERVER_ANNOUNCE_PLAYER_ACHIEVEMENTS}
      MAX_PLAYERS: ${MINECRAFT_SERVER_MAX_PLAYERS}
      PVP: ${MINECRAFT_SERVER_PVP}
      ENABLE_RCON: ${MINECRAFT_SERVER_ENABLE_RCON}
      RCON_PASSWORD: ${MINECRAFT_SERVER_RCON_PASSWORD}
      RCON_PORT: ${MINECRAFT_SERVER_RCON_PORT}
      SERVER_PORT: ${MINECRAFT_SERVER_SERVER_PORT}
      ALLOW_FLIGHT: ${MINECRAFT_SERVER_ALLOW_FLIGHT}
      MAX_WORLD_SIZE: ${MINECRAFT_SERVER_MAX_WORLD_SIZE}
      MAX_BUILD_HEIGHT: ${MINECRAFT_SERVER_MAX_BUILD_HEIGHT}
      SPAWN_ANIMALS: ${MINECRAFT_SERVER_SPAWN_ANIMALS}
      SPAWN_MONSTERS: ${MINECRAFT_SERVER_SPAWN_MONSTERS}
      SPAWN_NPCS: ${MINECRAFT_SERVER_SPAWN_NPCS}
      SPAWN_PROTECTION: ${MINECRAFT_SERVER_SPAWN_PROTECTION}
      VIEW_DISTANCE: ${MINECRAFT_SERVER_VIEW_DISTANCE}
      ONLINE_MODE: ${MINECRAFT_SERVER_ONLINE_MODE}
      SNOOPER_ENABLED: ${MINECRAFT_SERVER_SNOOPER_ENABLED}
      ENABLE_COMMAND_BLOCK: ${MINECRAFT_SERVER_ENABLE_COMMAND_BLOCK}
      WHITELIST: ${MINECRAFT_SERVER_WHITELIST}
      OPS: ${MINECRAFT_SERVER_OPS}
      TZ: ${MINECRAFT_SERVER_SERVER_TIMEZONE}
    networks:
      - minecraft-server-network
    ports:
      - "${MINECRAFT_SERVER_SERVER_PORT}:${MINECRAFT_SERVER_SERVER_PORT}"
    restart: unless-stopped

  backups:
    image: ${MINECRAFT_SERVER_BACKUP_IMAGE_TAG}
    environment:
      RCON_HOST: minecraft-server
      RCON_PORT: ${MINECRAFT_SERVER_RCON_PORT}
      RCON_PASSWORD: ${MINECRAFT_SERVER_RCON_PASSWORD}
      SERVER_PORT: ${MINECRAFT_SERVER_SERVER_PORT}
      SRC_DIR: ${DATA_PATH}
      BACKUP_METHOD: ${BACKUP_METHOD}
      BACKUP_INTERVAL: ${MINECRAFT_SERVER_BACKUP_INTERVAL}
      PRUNE_BACKUPS_DAYS: ${MINECRAFT_SERVER_PRUNE_BACKUPS_DAYS}
      INITIAL_DELAY: ${MINECRAFT_SERVER_INITIAL_DELAY}
      TZ: ${MINECRAFT_SERVER_SERVER_TIMEZONE}
    volumes:
    - ./minecraft-server-data:${DATA_PATH}:ro
    - ./minecraft-server-data-backups:${MINECRAFT_SERVER_BACKUPS_PATH}
    networks:
      - minecraft-server-network
    restart: unless-stopped
    depends_on:
      minecraft-server:
        condition: service_healthy
